version: "3.9"

services:
  mongo:
    image: mongo
    container_name: knote-mongo
    restart: always
    ports:
      - 27017:27017

  api:
    container_name: knote-api
    build:
      context: ./
    environment:
      - MONGO_URL=mongodb://mongo:27017/dev
    ports:
      - 3000:3000
